FROM golang:1.21.0 as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download && go mod verify

COPY . .

RUN make wasm

ARG VERSION
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=$VERSION" -o maze-wars_app ./cmd/server/
ENTRYPOINT ["/app/maze-wars_app"]
