FROM golang:1.20.8 as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download && go mod verify

COPY . .

RUN make wasm

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o maze-wars_app ./cmd/server/
ENTRYPOINT ["/app/maze-wars_app"]
