services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.7.0
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      maze-wars:
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion:2.5.2
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      maze-wars:
    restart: always

  maze-wars:
    build:
      context: ..
      dockerfile: docker/Dockerfile.maze-wars.prod
      args:
        VERSION: ${VERSION}
    expose:
      - 3000
    environment:
      - PORT=3000
      - VIRTUAL_HOST=maze-wars.yawpgames.com
      - LETSENCRYPT_HOST=maze-wars.yawpgames.com
      - LETSENCRYPT_EMAIL=info@yawpgames.com
    restart: on-failure
    networks:
      maze-wars:


  # Metrics
  grafana:
    image: grafana/grafana:11.5.2
    user: "472"
    depends_on:
      - prometheus
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - /home/maze-wars/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./data/grafana/config.monitoring
    networks:
      maze-wars:
    restart: always
    environment:
      - PORT=3000
      - VIRTUAL_HOST=metrics-maze-wars.yawpgames.com
      - LETSENCRYPT_HOST=metrics-maze-wars.yawpgames.com
      - LETSENCRYPT_EMAIL=info@yawpgames.com

  prometheus:
    image: prom/prometheus:v3.2.1
    volumes:
      - /home/maze-wars/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    expose:
      - 9090
    links:
      - cadvisor:cadvisor
    depends_on:
      - cadvisor
    networks:
      maze-wars:
    restart: always

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.9.0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    expose:
      - 9100
    networks:
      maze-wars:
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      maze-wars:
    restart: always

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
  prometheus_data:
  grafana_data:

