// Code generated by "enumer -type=Direction -transform=lower -output=direction_string.go"; DO NOT EDIT.

package utils

import (
	"fmt"
	"strings"
)

const _DirectionName = "updownleftright"

var _DirectionIndex = [...]uint8{0, 2, 6, 10, 15}

const _DirectionLowerName = "updownleftright"

func (i Direction) String() string {
	if i < 0 || i >= Direction(len(_DirectionIndex)-1) {
		return fmt.Sprintf("Direction(%d)", i)
	}
	return _DirectionName[_DirectionIndex[i]:_DirectionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DirectionNoOp() {
	var x [1]struct{}
	_ = x[Up-(0)]
	_ = x[Down-(1)]
	_ = x[Left-(2)]
	_ = x[Right-(3)]
}

var _DirectionValues = []Direction{Up, Down, Left, Right}

var _DirectionNameToValueMap = map[string]Direction{
	_DirectionName[0:2]:        Up,
	_DirectionLowerName[0:2]:   Up,
	_DirectionName[2:6]:        Down,
	_DirectionLowerName[2:6]:   Down,
	_DirectionName[6:10]:       Left,
	_DirectionLowerName[6:10]:  Left,
	_DirectionName[10:15]:      Right,
	_DirectionLowerName[10:15]: Right,
}

var _DirectionNames = []string{
	_DirectionName[0:2],
	_DirectionName[2:6],
	_DirectionName[6:10],
	_DirectionName[10:15],
}

// DirectionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DirectionString(s string) (Direction, error) {
	if val, ok := _DirectionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DirectionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Direction values", s)
}

// DirectionValues returns all values of the enum
func DirectionValues() []Direction {
	return _DirectionValues
}

// DirectionStrings returns a slice of all String values of the enum
func DirectionStrings() []string {
	strs := make([]string, len(_DirectionNames))
	copy(strs, _DirectionNames)
	return strs
}

// IsADirection returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Direction) IsADirection() bool {
	for _, v := range _DirectionValues {
		if i == v {
			return true
		}
	}
	return false
}
