// Code generated by "enumer -type=Environment -transform=lower -json -transform=snake -output=environment_string.go"; DO NOT EDIT.

package environment

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _EnvironmentName = "terrestrialaerial"

var _EnvironmentIndex = [...]uint8{0, 11, 17}

const _EnvironmentLowerName = "terrestrialaerial"

func (i Environment) String() string {
	if i < 0 || i >= Environment(len(_EnvironmentIndex)-1) {
		return fmt.Sprintf("Environment(%d)", i)
	}
	return _EnvironmentName[_EnvironmentIndex[i]:_EnvironmentIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EnvironmentNoOp() {
	var x [1]struct{}
	_ = x[Terrestrial-(0)]
	_ = x[Aerial-(1)]
}

var _EnvironmentValues = []Environment{Terrestrial, Aerial}

var _EnvironmentNameToValueMap = map[string]Environment{
	_EnvironmentName[0:11]:       Terrestrial,
	_EnvironmentLowerName[0:11]:  Terrestrial,
	_EnvironmentName[11:17]:      Aerial,
	_EnvironmentLowerName[11:17]: Aerial,
}

var _EnvironmentNames = []string{
	_EnvironmentName[0:11],
	_EnvironmentName[11:17],
}

// EnvironmentString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EnvironmentString(s string) (Environment, error) {
	if val, ok := _EnvironmentNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EnvironmentNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Environment values", s)
}

// EnvironmentValues returns all values of the enum
func EnvironmentValues() []Environment {
	return _EnvironmentValues
}

// EnvironmentStrings returns a slice of all String values of the enum
func EnvironmentStrings() []string {
	strs := make([]string, len(_EnvironmentNames))
	copy(strs, _EnvironmentNames)
	return strs
}

// IsAEnvironment returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Environment) IsAEnvironment() bool {
	for _, v := range _EnvironmentValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Environment
func (i Environment) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Environment
func (i *Environment) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Environment should be a string, got %s", data)
	}

	var err error
	*i, err = EnvironmentString(s)
	return err
}
